### ISSUE TITLE
v3.7.0 でインストール時に強制終了するようになった

### ISSUE THREAD

**Issue by para7** [team-apm/apm#1447]
## バグの説明

v3.7.0にアップデートしたところ、一部パッケージのインストール中にapmが終了してしまうようになりました。

## 再現手順

動作を再現する手順:

1. apmを使ってAviUtlをクリーンインストール
2. 以下のパッケージのインストール時に強制終了

- ease / ePi氏
- トラックバー対応イージングスクリプト / UndoFish氏

## 期待していた動作

インストール出来ること

## デスクトップ（以下の情報を入力してください）:

- OS: Windows 10
- Version: 22H2

## 補足説明

v3.6.3 に戻したところ正常にインストールできました。

**Comment by hal-shu-sato** [comment]
こちらの問題ですが、今日公開しましたv3.7.1にて修正しました。
まだ発生するようでしたら、ご連絡ください。

**Comment by para7** [comment]
@hal-shu-sato 
v3.7.1で解消されたことを確認いたしました。
迅速なご対応ありがとうございます！

**Comment by hal-shu-sato** [comment]
解決したのでcloseします

**Comment by hal-shu-sato** [comment]
解決したのでcloseします。

**Comment by yumetodo** [comment]
ref:
- #1423
- #1428
