### ISSUE TITLE
Cannot read property 'getOwnerBrowserWindow' of null

### ISSUE THREAD

**Issue by yumetodo** [team-apm/apm#173]
## バグの説明

```
[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
TypeError: Cannot read property 'getOwnerBrowserWindow' of null
    at Function.n.fromWebContents (electron/js2c/browser_init.js:33:1573)
    at Session.listener (C:\Users\yumetodo\AppData\Local\apm\app-1.0.0\resources\app.asar\node_modules\electron-dl\index.js:68:64)
    at Session.emit (events.js:315:20)
```

## 再現手順

動作を再現する手順:

1. AviUtl.Package.Manager-1.0.0.Setup.exeを起動
2. 小さいベーシュ系背景のウィンドウが数秒間見え消える
2. エラーが出る

次回起動時には発生しない

## 期待していた動作

エラーが出ない

## スクリーンショット

![image](https://user-images.githubusercontent.com/10869046/136811743-c4569a54-b03b-4815-b598-bb18351bef53.png)

## デスクトップ（以下の情報を入力してください）:

- OS: Windows10 Home 21H1(19043.1237)
- Version:

**Comment by yumetodo** [comment]
当該コードをまだ読んでないのであれですがtimerつきretryをかけてみるとかが緩和策になるんですかね・・・

**Comment by mitosagi** [comment]
## 再現手順

動作を再現する手順:

1. 通信帯域を24kbpsに制限
2. AppData内のユーザーデータを削除
3. apmを起動

帯域はSoftPerfect Bandwidth Managerで絞りました。

**Comment by hal-shu-sato** [comment]
いろいろ調べていたところ、このissueを見つけました。
sindresorhus/electron-dl#42
`BrowserWindow.getFocusedWindow()`が原因かもしれません。
修正したPRを送ってみるので、テストお願いします。
