### ISSUE TITLE
TypeScript

### ISSUE THREAD

**Issue by hal-shu-sato** [team-apm/apm#313]
## Is your feature request related to a problem? Please describe.

I have been confused with type errors.
But I found TypeScript that will improve them.
What do you think of using TypeScript?

## Describe the solution you'd like

Use TypeScript.

## Additional context

Electron Forge supports it.
https://www.electronforge.io/templates/typescript-+-webpack-template

**Comment by mitosagi** [comment]
I'm interested to see how much Typescript can help reduce bugs. I think it's a good idea to use it.

**Comment by mitosagi** [comment]
I am planning to generate TypeScript type definitions from JSON Schema within apm-data and introduce them as dependencies of apm.
