### ISSUE TITLE
Separate plugins and script into other tabs

### ISSUE THREAD

**Issue by hal-shu-sato** [team-apm/apm#319]
## Is your feature request related to a problem? Please describe.

Recently, I have been very happy to see more and more data in the package.
But, showing too many packages causes difficulty in searchability.

## Describe the solution you'd like

Separate data into the `Plugins` tab and the `Scripts` tab on apm.

**Comment by mitosagi** [comment]
I think it would be good to implement it as a GUI to switch between tabs, while internally using the filter function.
