### ISSUE TITLE
Migrating from XML to JSON

### ISSUE THREAD

**Issue by mitosagi** [team-apm/apm#387]
## Is your feature request related to a problem? Please describe.

XML data does not have a one-to-one correspondence with javascript objects, so a parser is required; JSON files do not. Furthermore, the scripts in the `apm-data/util` folder are very complex in order to deal with XML.

## Describe the solution you'd like

Convert XML data and XML schema to JSON data and JSON schema.

## Describe alternatives you've considered

Leave it as it is.

## Additional context

In addition, it makes it easier to modify the data structure.

**Comment by hal-shu-sato** [comment]
These days, I think so too.
If we do that, we will release it as v3.
In addition, in v3, I would like to support the splitting of data files and change to edit data from GUI implementing validation such as apm-web.

**Comment by mitosagi** [comment]
If we have a JSON Schema, we can easily create a GUI using a library like [react-jsonschema-form](https://github.com/rjsf-team/react-jsonschema-form), so I will try to find out what libraries are available.

**Comment by mitosagi** [comment]
I am considering the following method for the migration process.
- apm v3 does not support XML, so the dataURL will be reset to the default setting when updating.
- Migration is performed for `packages.xml` generated by the script automatic installation.

**Comment by mitosagi** [comment]
It is hard to maintain two package maker codes, I am thinking of discontinuing apm internal package maker and maintain only apm-web. Any opinions would be appreciated.

**Comment by hal-shu-sato** [comment]
I agree with you.
apm is software for users so the package maker which is for developers is not necessary.
It is good to unify to apm-web.

**Comment by mitosagi** [comment]
The purpose of this issue has already been accomplished.
