### ISSUE TITLE
Garbled filename when unzipped

### ISSUE THREAD

**Issue by FOBshippingpoint** [team-apm/apm#680]
## Describe the bug
When I download a script, I will get garbled filename/folder in my script directory.

## To Reproduce

1. Go to `プラグイン&スクリプト` tab
2. Click on `AviUtlスクリプト一式`
3. Press `Download` button in BowlRoll's page
4. The message shows `インストール完了`

## Expected behavior
For example, in `./script/ANM_ssd` folder, the correct filename is `2値化ノイズ.anm`, but I got `2.anm` instead.

## Screenshots
In `./script/ANM_ssd`:
![圖片](https://user-images.githubusercontent.com/60565355/176684125-2c6435b0-f87e-480b-a0eb-eeae3edc8835.png)
The correct filename is:
![圖片](https://user-images.githubusercontent.com/60565355/176684341-f466acb0-952d-4cba-a77c-bbbd6acd324a.png)

## Desktop:

- OS: Windows 10
- OS Code Page: 950(chinese)
- Version: 3.2.0

## Additional context
The problem might caused by **Wrong Encoding Code Page**. When I use 7zip to unzip script.zip, I also got garbled filename/folder. But I can get correct result with code page 932(Shift JIS).

I tried to fix the problem in `src/lib/unzip.js` line 38:
```js
  const zipStream = extractFull(zipPath, targetPath, {
    $bin: process.platform === 'win32' ? pathTo7zipWin : pathTo7zipCross,
    overwrite: 'a',
    method: ['cp=932'], // https://sevenzip.osdn.jp/chm/cmdline/switches/method.htm
  });
```
But the result is not good. Both garbled file and correct file are in the folder:
![圖片](https://user-images.githubusercontent.com/60565355/176687342-84d34123-d93d-4fb7-bc01-c9818733e60c.png)

AviUtl is a very good software, but installing and setting is quiet annoying to me. APM solve the problem, so I really love the this project. 
P.S. Sorry for the bad grammar. I am not good at English and Japanese.

**Comment by mitosagi** [comment]
## To Reproduce (for Japanese users)
1. Configure the following settings

設定 > 時刻と言語 > 言語と地域 > 管理用言語の設定 > システムロケールの変更 > 中国語（繫体字、台湾）
``` powershell
# You can verify that the settings are correct in powershell.
> chcp
Active code page: 950
```

2. Install `AviUtlスクリプト一式`
